### ISSUE TITLE
error comes as customer clearance details is required.

### ISSUE THREAD

**Issue by piyushsharmajec** [five23/shipsync-community#1]
ERROR: Customs Clearance Detail is required

**Comment by five23** [comment]
Greetings, sorry for the slow response!

There are a number of reasons why a Clearance Detail may be rejected, but in this case it appears that the Detail isn't being included in the shipment request, hence the uninformative error message.

By default ShipSync automatically fills out the Clearance Detail information, using the "Magento Store Name" (System -> Configuration -> General -> Store Information -> Store Name) as the "Payor Company Name" and the "Shipping Settings Origin Phone" (System -> Configuration -> Sales -> Shipping Settings -> Origin -> Phone) as the "Payor Phone Number".  If these fields aren't present, ShipSync attempts to process the shipment without a Clearance Detail (as there are some cases where this is the desired behavior), and FedEx returns an error in the event that the Clearance Detail is required.

If you're shipping with a third party (broker), that's a whole other can of worms. ;)  Thankfully those error responses are much more verbose.

**Comment by ga3003** [comment]
I am stuck with this problem,but not getting any clue for this details. May I know how to get the correct "Payor Company Name" and "Payor Phone Number" which is mentioned in Fedex account. I have all the credentials of Fedex. Just tell me where I will get this detail so that I can use in Magento backend.
