### ISSUE TITLE
Rates not working for packages greater than 60 lbs.

### ISSUE THREAD

**Issue by tvanhuis** [five23/shipsync-community#10]
Installed on my 1.8.0.0 development site.  Seems to work fine, except for the fact that any of my products that have weights greater than 60 lbs are not showing any fedex methods/rates available, even though i have the max weight set to 150 lbs.  At 60 lbs, i get rates, but at 61 lbs - no rate.  i saw from some other posts that you need to make larger containers in the Configuration > Shipping Settings > ShipSync Packages, so I added 4 more levels of boxes all the way up to 150 lbs - but still nothing getting a shipping rate above 60 lbs.  help? Is there another setting i'm missing?  Thanks!

**Comment by jthn** [comment]
Do you have dimensions set for your products? You can try toggling off size
based packing in the config.

**Comment by tvanhuis** [comment]
Hmm - that is it.  Now I'm getting the rate.  However, the main reason I was installing was to get the dimensional weight rate, especially for expedited shipping.  Is that possible over 60 lbs?

**Comment by jthn** [comment]
What are the dimensions? It is probably pushing it to a freight sized
package with the size and weight.

**Comment by tvanhuis** [comment]
I think i see now that there might be a problem with the FedEx API.  I figured out the problem with the dimensional weight - i need to make sure that the last default shipping setting is 1" and 1 lb larger than my largest package.  Only problem now is that the FedEx API is tacking on an oversized item surcharge that is actually waved for us (from shipsync_rate.log):

[Surcharges] => Array
                                                (
                                                    [0] => stdClass Object
                                                        (
                                                            [SurchargeType] => OVERSIZE
                                                            [Level] => PACKAGE
                                                            [Description] => FedEx Ground Oversize III
                                                            [Amount] => stdClass Object
                                                                (
                                                                    [Currency] => USD
                                                                    [Amount] => 55.0
                                                                )

```
                                                    )
```

is there a way for me to programmatically remove the surcharge in this extension?

**Comment by jthn** [comment]
Definitely could be removed.

I'm wondering if it might be the api credentials that you are using.  Are
these test credentials or the authorized api creds for your account?
 Sometimes you can get credentials from your FedEx rep that are actually
test creds before they assign all features of your account.

**Comment by tvanhuis** [comment]
I'll definitely check on that - I'm using the production creds from our regular production site, but i've never had package dimensions included, so I think i'll email our rep and see what we can do.  Thanks for pointing me in the right direction.  

just in case, any hints on what file/files would need to be changed to drop the surcharges?  thanks again!

**Comment by five23** [comment]
Hey tvanhuis, I haven't been able to recreate this error on my end.   Any chance I could have a look at your site?

**Comment by tvanhuis** [comment]
Hi David,

I figured this out – it had to do with the dimensional weights of my packages on my large items being larger than 150 lbs.  I fixed it by adding the proper package sizes in the “Shipping Setting” section.  Thanks, though – this extension is working great for me so far.

Tim

**Comment by five23** [comment]
Awesome, glad it's working out for you..
