### ISSUE TITLE
MIssing Shipping Settings Origin Fields

### ISSUE THREAD

**Issue by sjcarr2014** [five23/shipsync-community#11]
Hello,

I have installed ShipSync (shipsync-community-0.5.0.1_RC1) into Magento 1.8.1.0 and setup our credentials with FedEx for testing.  In step 5 of the readme Installation section it says:
1. Navigate to "System-&gt;Configuration-&gt;Sales-&gt;Shipping Settings-&gt;Origin" and fill out your company's Country, Region/State, ZIP/Postal Code, City, Address, and Phone. Note: these fields are required for FedEx's API to work.

However, I do not have a field in that section for Phone.  I do have Street Address then also Street Address Line 2 and Street Address Line 3.  

I have the information I can complete in these fields.  When I try to "Create Shipment" from the order screen I get these errors:

ERROR: Invalid Shipper streetLine 1
ERROR: RequestedShipment Shipper contact - phoneNumber is required

I can only imagine these two things are related.  Please advise.

-Steven

**Comment by jthn** [comment]
Shipsync adds that field.  Make sure that you have flushed your
configuration cache and try again.

**Comment by sjcarr2014** [comment]
I refreshed those again and it did not change.  I also resintalled the files and refreshed/flushed the cashes to no effect.  Should I be trying with a package other than shipsync-community-0.5.0.1_RC1?

Thanks for your help?

**Comment by five23** [comment]
Verified that this was in fact a bug with RC1.

Here's an updated release package to address the issue :

https://github.com/five23/shipsync-community/releases/tag/0.5.0.3_RC3

**Comment by sjcarr2014** [comment]
Awesome.  I will try this one now.

**Comment by sjcarr2014** [comment]
Success!  Thanks for taking care of us so quickly.
