### ISSUE TITLE
Length, Width, and Height attributes not installing with ShipSync V5

### ISSUE THREAD

**Issue by hgomes13** [five23/shipsync-community#12]
CE 1.7.0.2 with custom theme. installing V5 doesn't seem to add the attributes "length, height, and width" to our Magento installation. Installing v5 on a fresh instal of CE 1.7.0.2 however works, and on a fresh CE 1.8.1.0

this inherently breaks the rate request to FedEx to get rates based on dimensions. I've tried installing the attributes manually, but that doesn't fix it. (shot in the dark)

I've taken a look into the source and I think there are 2 problems with it: typo on "package.php" line 263 missing a "v" in value; but else I have no clue how the EAV / attribute dependencies work or whether there is a error log to check.

**Comment by five23** [comment]
Verified bug.

I'll include a fix in the next commit (as well as confirm backwards compatibility with 1.7)

**Comment by hgomes13** [comment]
Greatly appreciated guys! When will the next commit be?

**Comment by GBVM** [comment]
Looking forward to seeing a fix for this as well. Can you please let me know an estimated time for this. Im willing to pay to have this taken care of right away.

**Comment by hgomes13** [comment]
Any luck with the bug fix?

**Comment by five23** [comment]
Hey guys, sorry this has been delayed ...  I'm sooooo close now to a stable version, and then I'll be focusing on backwards compatibility.

I can do a custom mod to get you guys going in the meantime if needed.  Email me : david@ecomatics.net.

Otherwise, it'll probably be another week or so before I start testing with Magento 1.5-1.7

**Comment by five23** [comment]
ShipSync is working properly on Magento 1.7.x now, and presumably should now work with versions as far back as 1.5.x.
