### ISSUE TITLE
The payor's account number is invalid

### ISSUE THREAD

**Issue by hiteshagarwal** [five23/shipsync-community#2]
I try everything and my credentials were working fine before installing it.
But now it shows "ERROR: ShippingChargesPayment Payor - The payor's account number is invalid" when I try to create shipment with my production settings but it was working fine with test settings. Please help

**Comment by five23** [comment]
Greetings, sorry for the slow response.  

This error message comes directly from FedEx (see the table linked below), and indicates that the requested service isn't enabled for your account.

http://www.fedex.com/us/developer/product/WebServices/MyWebHelp/ReferenceTables/r_ErrorCodesShipService.html

By default only Rating is enabled for Production credentials, so if you're able to get rates on the front-end but not able to ship packages on the back end, then you'll need to have Shipment services enabled for your account.  Contact your FedEx rep and send them copies of your test labels and they'll be able to turn that on for you.
