### ISSUE TITLE
Question: "Ground and Home Delivery must be selected independently"?

### ISSUE THREAD

**Issue by bahoo** [five23/shipsync-community#25]
This comment appears in the admin when selecting which method to use as Free Shipping.

What does this mean, exactly?

**Comment by jthn** [comment]
If memory serves, it is that Ground applies to business and Home Delivery applies to residences, so you need to select both to allow free shipping to everyone.

**Comment by five23** [comment]
Yup, ontek is correct.

In regards to the language of the config tool-tip, many versions ago it may have been true, but the functionality has changed quite a bit since then and the tool-tip now seems downright nonsensical. Removed. ;)

Thanks for the good eye bahoo.
